spring.application.name=user

spring.datasource.url=jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@Ivander060405
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Server Configuration
server.port=8084

# JWT Configuration
app.jwt.secret=v7S8D9fghjklMnBvCxzQWERTYUIOPasdfghjklmnbvcxz1234567890QWERTYUIOP
app.jwt.expiration=3600000